#!/bin/sh

cd extension
echo "Running ESLint..."
npm run eslint
if [ $? != 0 ]
then
    echo "❌ Linting failed! Rejecting commit."
    exit 1
fi

echo "Running unit tests..."
npm run test
if [ $? != 0 ]
then
    echo "❌ Unit tests failed! Rejecting commit."
    exit 1
fi

echo "✅ Pre-commit checks passed! Proceeding with commit."